#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REMOTE_USER="${REMOTE_USER:-root}"
REMOTE_HOST="${REMOTE_HOST:-159.223.53.88}"
REMOTE_CONFIG_PATH="${REMOTE_CONFIG_PATH:-/root/deploy-config.tar.gz}"
REMOTE_IMAGE_PATH="${REMOTE_IMAGE_PATH:-/root/app-image.tar.gz}"
REMOTE_SCRIPT_PATH="${REMOTE_SCRIPT_PATH:-/root/remote-deploy.sh}"
APP_IMAGE_NAME="${APP_IMAGE_NAME:-jp-n1:deploy}"

REMOTE_USER="$REMOTE_USER" REMOTE_HOST="$REMOTE_HOST" REMOTE_CONFIG_PATH="$REMOTE_CONFIG_PATH" REMOTE_IMAGE_PATH="$REMOTE_IMAGE_PATH" APP_IMAGE_NAME="$APP_IMAGE_NAME" \
  "$PROJECT_ROOT/scripts/package-and-upload.sh"
scp "$PROJECT_ROOT/scripts/remote-deploy.sh" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_SCRIPT_PATH"
ssh "$REMOTE_USER@$REMOTE_HOST" "chmod +x $REMOTE_SCRIPT_PATH && CONFIG_ARCHIVE_PATH=$REMOTE_CONFIG_PATH IMAGE_ARCHIVE_PATH=$REMOTE_IMAGE_PATH APP_IMAGE_NAME=$APP_IMAGE_NAME $REMOTE_SCRIPT_PATH"
